version: '3.1'

networks:
    # external/public facing network
    #   for reverse proxies and similar
    public:
        ipam:
            config:
                - subnet: 172.29.90.0/24

    # endpoint layer network
    #   for endpoint layer microservices
    ep:
        ipam:
            config:
                - subnet: 172.29.91.0/24

    # services layer network
    #   for general service layer microservices
    default:
        ipam:
            config:
                - subnet: 172.29.95.0/24

services:
    nginx:
        image: qs/nginx
        networks:
            - public
            - ep
        ports:
            - ${qs_http_port}:80
            - ${qs_https_port}:443
        depends_on:
            - qtms-ep-web
            # - qs-app-ui
        deploy:
            placement:
                constraints:
                    - engine.labels.com.qtort.role == worker

    broker1:
        image: rabbitmq:management
        networks:
            - default
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ${qs_data}/broker1-data:/var/lib/rabbitmq
        deploy:
            replicas: 0
            placement:
                constraints:
                    - engine.labels.com.qtort.role == broker

    # mongo1:
    #     image: mongo
    #     networks:
    #         - default
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - ${qs_data}/mongo1-data:/data/db
    #     deploy:
    #         replicas: 0
    #         placement:
    #             constraints:
    #                 - engine.labels.com.qtort.role == db

    qtms-ep-web:
        image: docker.qtort.com/qs/qtms-ep-web
        entrypoint:
            - node
            - /opt/qtms-ep-web
            - --broker=${qs_broker}
            - --defaultExchange=${qs_ep_exchange}
            - --ll=${qs_loglevel}
        networks:
            ep:
                ipv4_address: 172.29.91.21
            default:
        depends_on:
            - broker1

    # qs-app-ui:
    #     # image: qs/qs-app-ui
    #     image: docker.qtort.com/qs/qs-app-ui
    #     networks:
    #         ep:
    #             ipv4_address: 172.29.91.23
    #
    # persist-mongodb:
    #     image: qs/persist-mongodb
    #     entrypoint:
    #         - node
    #         - /opt/persist-mongodb
    #         - --broker=${qs_broker}
    #         - --mongo=${qs_mongo}
    #         - --ll=${qs_loglevel}
    #     networks:
    #         - default
    #     depends_on:
    #         - broker1
    #         - mongo1
    #
    # auth-pep:
    #     image: qs/auth-pep
    #     entrypoint:
    #         - node
    #         - /opt/auth-pep
    #         - --broker=${qs_broker}
    #         - --ll=${qs_loglevel}
    #         - --identityServer=${qs_auth_identity_server}
    #         - --domain=${qs_auth_domain}
    #     depends_on:
    #         - broker1
    #
    # auth-identity-wso2is:
    #     image: qs/auth-identity-wso2is
    #     entrypoint:
    #         - node
    #         - /opt/auth-identity-wso2is
    #         - --broker=${qs_broker}
    #         - --ll=${qs_loglevel}
    #         - --identityServer=${qs_auth_identity_server}
    #         - --domain=${qs_auth_domain}
    #     depends_on:
    #         - broker1
